[package]
name = "game_stat"
version = "0.3.6"
edition = "2021"
categories = ["game-development"]
keywords = ["gamedev", "stats"]
license = "MIT OR Apache-2.0"
readme = "README.md"
description = "a library for handling stats that can change with modifiers, most commonly seen in games"
repository = "https://github.com/TanTanDev/game_stat.git"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive", "rc"] }
tinyvec = { version = "1.6", features = ["alloc", "rustc_1_55"] }
bevy_reflect = { version = "0.14.2", optional = true }

[features]
default = []
sync = []
serde = ["dep:serde"]
reflect = ["dep:bevy_reflect"]
